spring:
  application:
    name: pcidss

  data:
    redis:
      client-type: lettuce
      lettuce:
        pool:
          enabled: true

  sql:
    init:
      mode: never

  config:
    import: file:../conf/config.yml

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [%X{traceId:-},%X{spanId:-}] - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [%X{traceId:-},%X{spanId:-}] - %msg%n'
