spring:
  application:
    name: pcidss-poc

  data:
    redis:
      client-type: lettuce
      url: redis://localhost:6379
      lettuce:
        pool:
          enabled: true
  sql:
    init:
      mode: never

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [%X{traceId:-},%X{spanId:-}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [%X{traceId:-},%X{spanId:-}] - %msg%n"

antifraud:
  base-url: http://localhost:8081