#!/bin/bash

JAR_FILE="../libs/@JAR_NAME@"
JAVA_OPTS="-Xms512m -Xmx1G"

# Determine the Java command to use to start the JVM
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Ask passwords
read -sp "Please enter keystore password: " keystore_pass
echo
read -sp "And key password: " key_pass
echo

exec "$JAVACMD" \
  $JAVA_OPTS \
  -jar "$JAR_FILE" \
  "--keystore.password=$keystore_pass" \
  "--keystore.keyPassword=$key_pass" "$0"